"""Verify per-file standard provenance rows for one source intake report/run.

This script is intentionally read-only against DB tables.
It validates that each selected source file has at least one provenance row
matching expected source metadata.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from sqlalchemy import and_, select

# Ensure backend root is importable when running script file directly.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app.db.session import SessionLocal
from app.models.provenance import Provenance
from scripts.experimental.icloud_common import now_stamp, now_utc_iso, report_root


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify per-file provenance rows for one source intake run.")
    parser.add_argument(
        "--source-intake-report",
        type=str,
        required=True,
        help="Path to source_intake_<run>.json generated by run_pipeline.",
    )
    parser.add_argument(
        "--report-path",
        type=str,
        default=None,
        help="Optional output path for verification report JSON.",
    )
    return parser.parse_args()


def _default_report_path() -> Path:
    root = report_root()
    root.mkdir(parents=True, exist_ok=True)
    return root / f"icloud_provenance_verify_{now_stamp()}.json"


def _load_source_intake_report(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _verify(report_data: dict) -> dict:
    selected_files = list(report_data.get("selected_files", []) or [])
    source_label = report_data.get("source_label")
    ingestion_source_id = report_data.get("ingestion_source_id")
    ingestion_run_id = report_data.get("ingestion_run_id")

    db_session = SessionLocal()
    try:
        per_file: list[dict] = []
        found_count = 0

        for source_path in selected_files:
            query = (
                select(Provenance)
                .where(
                    and_(
                        Provenance.source_path == source_path,
                        Provenance.ingestion_run_id == ingestion_run_id,
                    )
                )
                .order_by(Provenance.id.asc())
            )
            rows = list(db_session.scalars(query).all())

            strict_rows = [
                row
                for row in rows
                if row.source_label == source_label and row.ingestion_source_id == ingestion_source_id
            ]

            matched_row = strict_rows[0] if strict_rows else None
            provenance_found = matched_row is not None
            if provenance_found:
                found_count += 1

            per_file.append(
                {
                    "filename": Path(source_path).name,
                    "source_path": source_path,
                    "asset_sha256": matched_row.asset_sha256 if matched_row else None,
                    "provenance_found": provenance_found,
                    "ingestion_source_id": matched_row.ingestion_source_id if matched_row else None,
                    "source_label": matched_row.source_label if matched_row else None,
                    "source_relative_path": matched_row.source_relative_path if matched_row else None,
                    "matching_rows_count": len(strict_rows),
                    "any_rows_for_path_count": len(rows),
                }
            )

        missing_count = len(selected_files) - found_count
        return {
            "generated_at_utc": now_utc_iso(),
            "source_label": source_label,
            "ingestion_source_id": ingestion_source_id,
            "ingestion_run_id": ingestion_run_id,
            "selected_files_count": len(selected_files),
            "provenance_found_count": found_count,
            "provenance_missing_count": missing_count,
            "all_files_have_provenance": missing_count == 0,
            "per_file": per_file,
        }
    finally:
        db_session.close()


def main() -> int:
    args = _parse_args()
    source_intake_path = Path(args.source_intake_report).expanduser().resolve()
    output_path = Path(args.report_path).expanduser().resolve() if args.report_path else _default_report_path()

    report_data = _load_source_intake_report(source_intake_path)
    verification = _verify(report_data)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(verification, indent=2), encoding="utf-8")

    print("Source intake provenance verification complete.")
    print(f"Source intake report: {source_intake_path}")
    print(f"Verification report: {output_path}")
    print(
        "Selected files: "
        f"{verification['selected_files_count']} | Provenance found: {verification['provenance_found_count']} "
        f"| Missing: {verification['provenance_missing_count']}"
    )

    return 0 if verification["all_files_have_provenance"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
