"""Controlled vocabulary for content tagging.

Raw ImageNet class names are mapped to a curated whitelist of labels.
Each whitelisted label is assigned a tag_type: "object" or "scene".

Only labels present in TAG_WHITELIST are persisted. Any raw model output
not covered by LABEL_MAP or not in TAG_WHITELIST is discarded.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Whitelist: expanded controlled vocabulary and tag_type assignments
# ---------------------------------------------------------------------------

TAG_WHITELIST: dict[str, str] = {
    # --- Objects ---
    "person": "object",
    "baby": "object",
    "group": "object",
    "dog": "object",
    "cat": "object",
    "bird": "object",
    "horse": "object",
    "fish": "object",
    "car": "object",
    "truck": "object",
    "van": "object",
    "bicycle": "object",
    "motorcycle": "object",
    "airplane": "object",
    "boat": "object",
    "ship": "object",
    "bus": "object",
    "train": "object",
    "food": "object",
    "dessert": "object",
    "cake": "object",
    "flower": "object",
    "tree": "object",
    "building": "object",
    "house": "object",
    "bridge": "object",
    "tower": "object",
    "monument": "object",
    "book": "object",
    "computer": "object",
    "phone": "object",
    "television": "object",
    "camera": "object",
    "bottle": "object",
    "cup": "object",
    "plate": "object",
    "bowl": "object",
    "chair": "object",
    "table": "object",
    "sofa": "object",
    "bed": "object",
    "lamp": "object",
    "backpack": "object",
    "suitcase": "object",
    "toy": "object",
    "instrument": "object",
    "medical": "object",
    "clothing": "object",
    "hat": "object",
    "sunglasses": "object",
    "ball": "object",
    "racket": "object",
    # --- Scenes ---
    "beach": "scene",
    "coast": "scene",
    "waterfront": "scene",
    "harbor": "scene",
    "mountain": "scene",
    "forest": "scene",
    "garden": "scene",
    "park": "scene",
    "sky": "scene",
    "sunset": "scene",
    "snow": "scene",
    "desert": "scene",
    "city": "scene",
    "street": "scene",
    "indoor": "scene",
    "outdoor": "scene",
    "kitchen": "scene",
    "bathroom": "scene",
    "bedroom": "scene",
    "living_room": "scene",
    "party": "scene",
    "wedding": "scene",
    "restaurant": "scene",
    "stadium": "scene",
    "playground": "scene",
    "camping": "scene",
    "lake": "scene",
    "river": "scene",
    "waterfall": "scene",
    "ocean": "scene",
}

# ---------------------------------------------------------------------------
# Label map: raw ImageNet / timm class name  →  whitelist label
# Entries without a mapping fall through unchanged (matched directly against
# TAG_WHITELIST keys before being discarded).
# ---------------------------------------------------------------------------

LABEL_MAP: dict[str, str] = {
    # People and social
    "groom":                        "wedding",
    "bridegroom":                   "wedding",
    "bride":                        "wedding",
    "newborn":                      "baby",
    "infant":                       "baby",
    "dining_table":                 "table",
    # Animals
    "dog":                          "dog",
    # Animals
    "golden_retriever":             "dog",
    "labrador_retriever":           "dog",
    "german_shepherd":              "dog",
    "poodle":                       "dog",
    "beagle":                       "dog",
    "bulldog":                      "dog",
    "tabby":                        "cat",
    "persian_cat":                  "cat",
    "siamese_cat":                  "cat",
    "robin":                        "bird",
    "parrot":                       "bird",
    "macaw":                        "bird",
    "american_robin":               "bird",
    "albatross":                    "bird",
    "thoroughbred":                 "horse",
    "goldfish":                     "fish",
    "tench":                        "fish",
    "great_white_shark":            "fish",
    # Vehicles
    "pickup":                       "truck",
    "moving_van":                   "van",
    "police_van":                   "van",
    "cab":                          "car",
    "taxi":                         "car",
    "sports_car":                   "car",
    "convertible":                  "car",
    "minivan":                      "car",
    "limousine":                    "car",
    "jeep":                         "car",
    "racing_car":                   "car",
    "mountain_bike":                "bicycle",
    "moped":                        "motorcycle",
    "airliner":                     "airplane",
    "warplane":                     "airplane",
    "aircraft_carrier":             "ship",
    "liner":                        "ship",
    "canoe":                        "boat",
    "sailboat":                     "boat",
    "speedboat":                    "boat",
    "fireboat":                     "boat",
    "school_bus":                   "bus",
    "trolleybus":                   "bus",
    "freight_car":                  "train",
    "passenger_car":                "train",
    "electric_locomotive":          "train",
    # Food / objects
    "bakery":                       "food",
    "pizza":                        "food",
    "hamburger":                    "food",
    "hot_dog":                      "food",
    "cheeseburger":                 "food",
    "ice_cream":                    "food",
    "pretzel":                      "food",
    "bagel":                        "food",
    "ice_lolly":                    "dessert",
    "ice_cream":                    "dessert",
    "dough":                        "food",
    "birthday_cake":                "cake",
    "wedding_cake":                 "cake",
    "daisy":                        "flower",
    "rose":                         "flower",
    "sunflower":                    "flower",
    "tulip":                        "flower",
    "oak":                          "tree",
    "palm_tree":                    "tree",
    "pine":                         "tree",
    "fountain":                     "park",
    "palace":                       "building",
    "monastery":                    "building",
    "church":                       "building",
    "barn":                         "building",
    "castle":                       "building",
    "prison":                       "building",
    "prison_house":                 "building",
    "boathouse":                    "building",
    "cliff_dwelling":               "building",
    "skyscraper":                   "building",
    "lighthouse":                    "tower",
    "water_tower":                  "tower",
    "suspension_bridge":            "bridge",
    "steel_arch_bridge":            "bridge",
    "dam":                          "bridge",
    "obelisk":                      "monument",
    "stupa":                        "monument",
    "notebook_computer":            "computer",
    "desktop_computer":             "computer",
    "monitor":                      "television",
    "television":                   "television",
    "tv":                           "television",
    "camera":                       "camera",
    "reflex_camera":                "camera",
    "jigsaw_puzzle":                "toy",
    "brass":                        "instrument",
    "stethoscope":                  "medical",
    "cell_phone":                   "phone",
    "mobile_phone":                 "phone",
    "book_jacket":                  "book",
    "wine_bottle":                  "bottle",
    "water_bottle":                 "bottle",
    "beer_bottle":                  "bottle",
    "coffee_mug":                   "cup",
    "teacup":                       "cup",
    "plate_rack":                   "plate",
    "soup_bowl":                    "bowl",
    "mixing_bowl":                  "bowl",
    "couch":                        "sofa",
    "studio_couch":                 "sofa",
    "four_poster":                  "bed",
    "table_lamp":                   "lamp",
    "backpack":                     "backpack",
    "rucksack":                     "backpack",
    "suitcase":                     "suitcase",
    "briefcase":                    "suitcase",
    "pajama":                       "clothing",
    "miniskirt":                    "clothing",
    "maillot":                      "clothing",
    "bikini":                       "clothing",
    "sarong":                       "clothing",
    "swimming_trunks":              "clothing",
    "sweatshirt":                   "clothing",
    "suit":                         "clothing",
    "jersey":                       "clothing",
    "hoopskirt":                    "clothing",
    "diaper":                       "clothing",
    "feather_boa":                  "clothing",
    "bow_tie":                      "clothing",
    "bolo_tie":                     "clothing",
    "bonnet":                       "hat",
    "sombrero":                     "hat",
    "sunglasses":                   "sunglasses",
    "sunglass":                     "sunglasses",
    "soccer_ball":                  "ball",
    "basketball":                   "ball",
    "tennis_ball":                  "ball",
    "racket":                       "racket",
    "tennis_racket":                "racket",
    "swing":                        "playground",
    "carousel":                     "playground",
    "sleeping_bag":                 "camping",
    "window_shade":                 "indoor",
    "plunger":                      "bathroom",
    "tub":                          "bathroom",
    "shower_curtain":               "bathroom",
    "patio":                        "outdoor",
    "solar_dish":                   "outdoor",
    "bubble":                       "outdoor",
    "slot":                         "indoor",
    "vault":                        "indoor",
    "scoreboard":                   "stadium",
    "balance_beam":                 "stadium",
    "parallel_bars":                "stadium",
    "horizontal_bar":               "stadium",
    "rocking_chair":                "chair",
    "pool_table":                   "table",
    # Scenes
    "seashore":                     "beach",
    "shore":                        "beach",
    "breakwater":                   "waterfront",
    "pier":                         "waterfront",
    "dock":                         "harbor",
    "lakeside":                     "lake",
    "river":                        "river",
    "waterfall":                    "waterfall",
    "alp":                          "mountain",
    "cliff":                        "mountain",
    "valley":                       "mountain",
    "coral_reef":                   "ocean",
    "promontory":                   "mountain",
    "volcano":                      "mountain",
    "snowfield":                    "snow",
    "ice":                          "snow",
    "sandbar":                      "desert",
    "dune":                         "desert",
    "rainforest":                   "forest",
    "mangrove":                     "forest",
    "thicket":                      "forest",
    "geyser":                       "outdoor",
    "hot_spring":                   "outdoor",
    "campground":                   "camping",
    "street_sign":                  "street",
    "traffic_light":                "street",
    "flagpole":                     "street",
    "pole":                         "street",
    "park_bench":                   "park",
    "greenhouse":                   "garden",
    "shopping_mall":                "indoor",
    "restaurant":                   "restaurant",
    "library":                      "indoor",
    "cinema":                       "indoor",
    "urban_scene":                  "city",
    "downtown":                     "city",
    "kitchen":                      "kitchen",
}


def map_label(raw: str) -> str | None:
    """Map a raw model class name to a whitelisted label, or return None.

    Steps:
    1. Normalise: lowercase, replace spaces with underscores.
    2. Try LABEL_MAP lookup.
    3. Try direct whitelist key match.
    4. Return None if not found.
    """
    primary = re.split(r"[,;/]", raw, maxsplit=1)[0].strip()
    normalised = primary.lower().replace("-", "_").replace(" ", "_")
    mapped = LABEL_MAP.get(normalised, normalised)
    return mapped if mapped in TAG_WHITELIST else None


def get_tag_type(label: str) -> str:
    """Return the tag_type for a whitelisted label.  Raises KeyError if unknown."""
    return TAG_WHITELIST[label]
